export interface Employee {
  id: number;
  name: string;
  nationalId: string;
  email: string;
  position: string;
  role: string;
  branch: string;
  salary: number;
  contractType: string;
  contractStart: string;
  contractEnd?: string;
  lastLogin: string;
  absences: number;
  tags?: string[];
  permissions: string[];
  actions: { date: string; action: string }[];
  documents: { name: string; size: string }[];
  reports: {
    subject: string;
    text: string;
    date: string;
    submittedBy: string;
    classification?: string;
  }[];
  vacations: { start: string; end: string }[];
  sickLeaves: { start: string; end: string }[];
  stats: { punctuality: number; workedDays: number; lateArrivals: number };
  schedule: string;
  active: boolean;
}

export const mockEmployees: Employee[] = [
  {
    id: 1,
    name: 'Juan Pérez',
    nationalId: '8-123-456',
    email: 'juan@empresa.com',
    position: 'Contador',
    role: 'finanzas',
    branch: 'Sucursal 1',
    salary: 1200,
    contractType: 'Definido',
    contractStart: '2024-01-01',
    contractEnd: '2024-12-31',
    lastLogin: '2025-06-01',
    absences: 2,
    tags: ['activo', 'senior'],
    permissions: ['empleados:ver', 'empleados:editar'],
    actions: [{ date: '2025-05-01', action: 'Actualizó perfil' }],
    documents: [{ name: 'Contrato.pdf', size: '500KB' }],
    reports: [
      {
        subject: 'Retraso frecuente',
        text: 'Llegó tarde 3 veces esta semana.',
        date: '2025-05-15',
        submittedBy: 'RRHH',
        classification: 'Advertencia',
      },
    ],
    vacations: [{ start: '2025-07-01', end: '2025-07-10' }],
    sickLeaves: [],
    stats: { punctuality: 90, workedDays: 200, lateArrivals: 5 },
    schedule: 'Lun-Vie 8:00–17:00',
    active: true,
  },
         {
    id: 2,
    name: 'María Rodríguez',
    nationalId: '1-234-567',
    email: 'maria@empresa.com',
    position: 'Gerente de Ventas',
    role: 'ventas',
    branch: 'Sucursal 2',
    salary: 3500,
    contractType: 'Indefinido',
    contractStart: '2022-03-15',
    lastLogin: '2025-06-05',
    absences: 0,
    tags: ['lider', 'activo'],
    permissions: ['ventas:ver', 'ventas:editar', 'reportes:generar'],
    actions: [{ date: '2025-04-20', action: 'Realizó venta récord' }],
    documents: [{ name: 'Contrato.docx', size: '250KB' }],
    reports: [],
    vacations: [{ start: '2025-08-01', end: '2025-08-15' }],
    sickLeaves: [{ start: '2025-01-10', end: '2025-01-12' }],
    stats: { punctuality: 98, workedDays: 220, lateArrivals: 1 },
    schedule: 'Lun-Vie 9:00–18:00',
    active: true,
  },
  {
    id: 3,
    name: 'Carlos Sánchez',
    nationalId: '5-678-901',
    email: 'carlos@empresa.com',
    position: 'Desarrollador Senior',
    role: 'tecnologia',
    branch: 'Sucursal 3',
    salary: 4200,
    contractType: 'Indefinido',
    contractStart: '2021-11-01',
    lastLogin: '2025-06-07',
    absences: 3,
    tags: ['backend', 'fullstack'],
    permissions: ['sistema:admin', 'codigo:escribir'],
    actions: [{ date: '2025-05-30', action: 'Implementó nuevo módulo' }],
    documents: [
      { name: 'Acuerdo confidencial.pdf', size: '320KB' },
      { name: 'Certificaciones.zip', size: '1.2MB' },
    ],
    reports: [
      {
        subject: 'Problema seguridad',
        text: 'Identificó vulnerabilidad en API',
        date: '2025-05-10',
        submittedBy: 'Sistemas',
      },
    ],
    vacations: [],
    sickLeaves: [],
    stats: { punctuality: 85, workedDays: 210, lateArrivals: 8 },
    schedule: 'Lun-Vie 10:00–19:00',
    active: true,
  },
  {
    id: 4,
    name: 'Ana Martínez',
    nationalId: '3-456-789',
    email: 'ana@empresa.com',
    position: 'Recursos Humanos',
    role: 'rrhh',
    branch: 'Sucursal 1',
    salary: 2800,
    contractType: 'Definido',
    contractStart: '2024-02-10',
    contractEnd: '2024-12-10',
    lastLogin: '2025-06-06',
    absences: 1,
    tags: ['reclutamiento'],
    permissions: ['empleados:gestion', 'contratos:ver'],
    actions: [{ date: '2025-05-15', action: 'Contrató nuevo personal' }],
    documents: [{ name: 'Reglamento interno.pdf', size: '780KB' }],
    reports: [],
    vacations: [{ start: '2025-07-20', end: '2025-07-30' }],
    sickLeaves: [],
    stats: { punctuality: 95, workedDays: 195, lateArrivals: 3 },
    schedule: 'Lun-Vie 8:30–17:30',
    active: true,
  },
  {
    id: 5,
    name: 'Luis González',
    nationalId: '7-891-234',
    email: 'luis@empresa.com',
    position: 'Soporte Técnico',
    role: 'soporte',
    branch: 'Sucursal 2',
    salary: 1900,
    contractType: 'Indefinido',
    contractStart: '2023-06-20',
    lastLogin: '2025-06-04',
    absences: 5,
    tags: ['helpdesk'],
    permissions: ['tickets:gestion'],
    actions: [
      { date: '2025-05-22', action: 'Resolvió incidente crítico' },
      { date: '2025-04-10', action: 'Actualizó equipos' },
    ],
    documents: [],
    reports: [
      {
        subject: 'Equipo defectuoso',
        text: 'Reporte de laptops con fallas',
        date: '2025-05-28',
        submittedBy: 'Soporte',
        classification: 'Hardware',
      },
    ],
    vacations: [],
    sickLeaves: [{ start: '2025-03-01', end: '2025-03-05' }],
    stats: { punctuality: 88, workedDays: 180, lateArrivals: 9 },
    schedule: 'Lun-Vie 8:00–17:00',
    active: true,
  },
  {
    id: 6,
    name: 'Marta Díaz',
    nationalId: '2-345-678',
    email: 'marta@empresa.com',
    position: 'Diseñadora UI/UX',
    role: 'diseño',
    branch: 'Sucursal 3',
    salary: 3100,
    contractType: 'Indefinido',
    contractStart: '2022-09-01',
    lastLogin: '2025-06-07',
    absences: 2,
    tags: ['creativa', 'frontend'],
    permissions: ['diseño:editar', 'sistema:ver'],
    actions: [{ date: '2025-06-01', action: 'Presentó nuevo prototipo' }],
    documents: [{ name: 'Portafolio.pdf', size: '2.1MB' }],
    reports: [],
    vacations: [{ start: '2025-09-01', end: '2025-09-10' }],
    sickLeaves: [],
    stats: { punctuality: 92, workedDays: 205, lateArrivals: 4 },
    schedule: 'Lun-Vie 9:30–18:30',
    active: true,
  },
  {
    id: 7,
    name: 'Roberto Jiménez',
    nationalId: '9-876-543',
    email: 'roberto@empresa.com',
    position: 'Analista Financiero',
    role: 'finanzas',
    branch: 'Sucursal 1',
    salary: 3800,
    contractType: 'Definido',
    contractStart: '2024-03-01',
    contractEnd: '2025-03-01',
    lastLogin: '2025-06-03',
    absences: 0,
    tags: ['analisis'],
    permissions: ['finanzas:admin', 'reportes:generar'],
    actions: [{ date: '2025-05-25', action: 'Optimizó presupuesto' }],
    documents: [{ name: 'Certificación CPA.pdf', size: '1.5MB' }],
    reports: [],
    vacations: [],
    sickLeaves: [],
    stats: { punctuality: 99, workedDays: 215, lateArrivals: 0 },
    schedule: 'Lun-Vie 8:00–17:00',
    active: true,
  },
  {
    id: 8,
    name: 'Sofía Herrera',
    nationalId: '4-321-987',
    email: 'sofia@empresa.com',
    position: 'Marketing Digital',
    role: 'marketing',
    branch: 'Sucursal 2',
    salary: 2700,
    contractType: 'Indefinido',
    contractStart: '2021-07-15',
    lastLogin: '2025-06-06',
    absences: 4,
    tags: ['redes', 'creativa'],
    permissions: ['redes:gestion', 'contenido:crear'],
    actions: [{ date: '2025-05-20', action: 'Lanzó campaña exitosa' }],
    documents: [{ name: 'Estrategia Q3.docx', size: '450KB' }],
    reports: [],
    vacations: [{ start: '2025-10-10', end: '2025-10-20' }],
    sickLeaves: [{ start: '2025-02-01', end: '2025-02-03' }],
    stats: { punctuality: 87, workedDays: 198, lateArrivals: 7 },
    schedule: 'Lun-Vie 9:00–18:00',
    active: true,
  },
  {
    id: 9,
    name: 'Jorge Ramírez',
    nationalId: '6-555-444',
    email: 'jorge@empresa.com',
    position: 'Jefe de Logística',
    role: 'operaciones',
    branch: 'Sucursal 4',
    salary: 4100,
    contractType: 'Indefinido',
    contractStart: '2020-05-12',
    lastLogin: '2025-06-02',
    absences: 1,
    tags: ['almacen', 'senior'],
    permissions: ['logistica:admin', 'inventario:ver'],
    actions: [{ date: '2025-04-15', action: 'Redujo costos operativos' }],
    documents: [{ name: 'Certificación ISO.pdf', size: '890KB' }],
    reports: [
      {
        subject: 'Problema de inventario',
        text: 'Discrepancia en conteo físico',
        date: '2025-05-05',
        submittedBy: 'Auditoría',
      },
    ],
    vacations: [{ start: '2025-11-01', end: '2025-11-15' }],
    sickLeaves: [],
    stats: { punctuality: 94, workedDays: 230, lateArrivals: 2 },
    schedule: 'Lun-Vie 7:30–16:30',
    active: true,
  },
  {
    id: 10,
    name: 'Elena Castro',
    nationalId: '1-777-333',
    email: 'elena@empresa.com',
    position: 'Asistente Administrativo',
    role: 'administracion',
    branch: 'Sucursal 1',
    salary: 1600,
    contractType: 'Definido',
    contractStart: '2024-05-01',
    contractEnd: '2024-11-30',
    lastLogin: '2025-06-01',
    absences: 3,
    tags: ['nuevo'],
    permissions: ['documentos:gestion'],
    actions: [{ date: '2025-05-10', action: 'Organizó archivos' }],
    documents: [],
    reports: [],
    vacations: [],
    sickLeaves: [{ start: '2025-04-01', end: '2025-04-03' }],
    stats: { punctuality: 82, workedDays: 170, lateArrivals: 12 },
    schedule: 'Lun-Vie 8:00–17:00',
    active: true,
  },
  // ... (continuación con 20 empleados más)
  {
    id: 11,
    name: 'Pedro Rojas',
    nationalId: '8-222-111',
    email: 'pedro@empresa.com',
    position: 'Desarrollador Frontend',
    role: 'tecnologia',
    branch: 'Sucursal 3',
    salary: 3400,
    contractType: 'Indefinido',
    contractStart: '2023-01-15',
    lastLogin: '2025-06-07',
    absences: 2,
    tags: ['frontend', 'react'],
    permissions: ['codigo:escribir'],
    actions: [],
    documents: [{ name: 'Certificado React.pdf', size: '1.1MB' }],
    reports: [],
    vacations: [{ start: '2025-08-20', end: '2025-08-30' }],
    sickLeaves: [],
    stats: { punctuality: 91, workedDays: 202, lateArrivals: 5 },
    schedule: 'Lun-Vie 10:00–19:00',
    active: true,
  },
  {
    id: 12,
    name: 'Carmen Vega',
    nationalId: '3-999-000',
    email: 'carmen@empresa.com',
    position: 'Contadora Junior',
    role: 'finanzas',
    branch: 'Sucursal 2',
    salary: 2200,
    contractType: 'Definido',
    contractStart: '2024-04-01',
    contractEnd: '2025-04-01',
    lastLogin: '2025-06-04',
    absences: 0,
    tags: ['junior', 'activo'],
    permissions: ['finanzas:ver'],
    actions: [{ date: '2025-05-18', action: 'Auditoría completa' }],
    documents: [],
    reports: [],
    vacations: [],
    sickLeaves: [],
    stats: { punctuality: 97, workedDays: 185, lateArrivals: 1 },
    schedule: 'Lun-Vie 8:00–17:00',
    active: true,
  },
  {
    id: 13,
    name: 'Ricardo Mora',
    nationalId: '5-444-555',
    email: 'ricardo@empresa.com',
    position: 'Especialista SEO',
    role: 'marketing',
    branch: 'Sucursal 4',
    salary: 2900,
    contractType: 'Indefinido',
    contractStart: '2022-08-10',
    lastLogin: '2025-06-06',
    absences: 2,
    tags: ['seo', 'analitica'],
    permissions: ['seo:gestion'],
    actions: [{ date: '2025-05-22', action: 'Mejoró ranking 40%' }],
    documents: [{ name: 'Informe SEO.pdf', size: '680KB' }],
    reports: [],
    vacations: [{ start: '2025-12-01', end: '2025-12-10' }],
    sickLeaves: [],
    stats: { punctuality: 89, workedDays: 208, lateArrivals: 6 },
    schedule: 'Lun-Vie 9:00–18:00',
    active: true,
  },
  {
    id: 14,
    name: 'Isabel Chin',
    nationalId: '2-666-888',
    email: 'isabel@empresa.com',
    position: 'Jefa de Proyectos',
    role: 'tecnologia',
    branch: 'Sucursal 1',
    salary: 4700,
    contractType: 'Indefinido',
    contractStart: '2019-11-01',
    lastLogin: '2025-06-07',
    absences: 1,
    tags: ['scrum', 'lider'],
    permissions: ['proyectos:admin'],
    actions: [{ date: '2025-06-01', action: 'Entrega proyecto X' }],
    documents: [{ name: 'Certificación PMP.pdf', size: '1.8MB' }],
    reports: [],
    vacations: [{ start: '2025-07-15', end: '2025-07-30' }],
    sickLeaves: [{ start: '2025-01-20', end: '2025-01-23' }],
    stats: { punctuality: 96, workedDays: 225, lateArrivals: 3 },
    schedule: 'Lun-Vie 8:30–17:30',
    active: true,
  },
  {
    id: 15,
    name: 'Fernando Gutiérrez',
    nationalId: '7-111-222',
    email: 'fernando@empresa.com',
    position: 'Soporte Nivel 2',
    role: 'soporte',
    branch: 'Sucursal 3',
    salary: 2100,
    contractType: 'Definido',
    contractStart: '2024-06-01',
    contractEnd: '2024-12-31',
    lastLogin: '2025-06-05',
    absences: 6,
    tags: ['redes', 'junior'],
    permissions: ['tickets:gestion'],
    actions: [],
    documents: [],
    reports: [
      {
        subject: 'Actualización fallida',
        text: 'Error en actualización de servidores',
        date: '2025-05-30',
        submittedBy: 'Sistemas',
        classification: 'Crítico',
      },
    ],
    vacations: [],
    sickLeaves: [{ start: '2025-05-10', end: '2025-05-15' }],
    stats: { punctuality: 79, workedDays: 165, lateArrivals: 15 },
    schedule: 'Lun-Vie 8:00–17:00',
    active: true,
  },

  {
    id: 17,
    name: 'Laura Méndez',
    nationalId: '9-000-111',
    email: 'laura@empresa.com',
    position: 'Diseñadora Gráfica',
    role: 'diseño',
    branch: 'Sucursal 2',
    salary: 2600,
    contractType: 'Indefinido',
    contractStart: '2023-03-01',
    lastLogin: '2025-04-15',
    absences: 12,
    tags: ['inactivo'],
    permissions: ['diseño:ver'],
    actions: [{ date: '2025-03-10', action: 'Último proyecto' }],
    documents: [],
    reports: [],
    vacations: [],
    sickLeaves: [{ start: '2025-04-20', end: '2025-06-01' }],
    stats: { punctuality: 65, workedDays: 120, lateArrivals: 25 },
    schedule: 'Lun-Vie 9:00–18:00',
    active: false,
  },
];